name: 'Setup Java and Maven'
description: 'Setup Java and Maven for pipeline'
inputs:
  github-token:
    description: 'Token used to reach maven.pkg.github.com'
    required: true
  java-version:
    description: 'Java SDK version to use'
    required: false
    default: '25'
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.9.11'
  working-directory:
    description: 'Working directory to perform maven in'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Create maven .m2 settings
      uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d
      with:
        repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
        servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ inputs.github-token }}" }]'
        output_file: '${{ inputs.working-directory }}/settings.xml'
    - name: Set up JDK-${{ inputs.java-version }} with cache
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # ratchet:actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
        #cache-dependency-path: ${{ inputs.working-directory }}**/pom.xml
