name: Kjør knip
inputs:
  npmAuthToken:
    description: Token med `packages:read` for navikt organisasjonen
    required: true
  package-manager:
    required: true
    description: Hvilken package manager en skal bruke (pnpm|yarn)
  node-version:
    required: false
    description: Node version som brukes.
    default: "22"
  github-token:
    description: Token to use when adding comment to PR
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v4

    - uses: navikt/fp-gha-workflows/.github/actions/setup-yarnrc@main
      if: inputs.package-manager == 'yarn'
      with:
        npmAuthToken: ${{ inputs.npmAuthToken }}

    - uses: navikt/fp-gha-workflows/.github/actions/setup-npmrc@main
      if: inputs.package-manager == 'pnpm'
      with:
        npmAuthToken: ${{ inputs.npmAuthToken }}

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # ratchet:pnpm/action-setup@v2
      if: inputs.package-manager == 'pnpm'
      with:
        version: 10.18.3

    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # ratchet:actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - name: Yarn install
      if: inputs.package-manager == 'yarn'
      shell: bash
      run: |
        yarn install --immutable

    - name: Pnpm install
      if: inputs.package-manager == 'pnpm'
      shell: bash
      run: |
        pnpm install --frozen-lockfile

    - name: Run knip
      if: inputs.package-manager == 'yarn'
      shell: bash
      run: |
        yarn knip --no-exit-code --reporter=markdown > knip-report.md
        cat knip-report.md > $GITHUB_STEP_SUMMARY

    - name: Run knip
      if: inputs.package-manager == 'pnpm'
      shell: bash
      run: |
        pnpm knip --no-exit-code --reporter=markdown > knip-report.md
        cat knip-report.md > $GITHUB_STEP_SUMMARY

    - name: Delete previous comments from knip
      shell: bash
      continue-on-error: true
      run: gh pr comment ${{ github.event.pull_request.number }} --delete-last --yes
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Post knip report
      shell: bash
      run: |
        number_of_words=$(wc -w < knip-report.md)
        if [ $number_of_words -gt 3 ]; then        
          gh pr comment ${{ github.event.pull_request.number }} --body-file knip-report.md
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
