name: Setup yarn config
description: |-
  Konfigurerer yarn auth config for å hente `@navikt/*` og `@nais/*`-pakker fra
  GitHub Package Registry. Actionen autentiserer med den innebygde `github.token`,
  så den kallende jobben MÅ sette
  ```
  permissions:
    packages: read # for å hente `@navikt`/`@nais`-pakker
  ```

runs:
  using: composite
  steps:
    - name: Setup yarn config
      shell: bash
      run: |
        yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.navikt.npmAlwaysAuth true
        yarn config set npmScopes.navikt.npmAuthToken ${{ github.token }}
        yarn config set npmScopes.nais.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.nais.npmAlwaysAuth true
        yarn config set npmScopes.nais.npmAuthToken ${{ github.token }}
