name: Setup yarn config
description: Konfigurerer yarn auth config for å hente `@navikt/*`-pakker i github package registry
inputs:
  npmAuthToken:
    description: Token med `packages:read` for navikt organisasjonen
    required: true

runs:
  using: composite
  steps:
    - name: Setup yarn config
      shell: bash
      run: |
        yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.navikt.npmAlwaysAuth true
        yarn config set npmScopes.navikt.npmAuthToken ${{ inputs.npmAuthToken }}
