name: "Build and push docker image"
description: "Build and push docker image"
inputs:
  build-version:
    description: "Image tag for the docker image"
    required: true
  namespace:
    required: false
    description: "NAV team"
    default: "teamforeldrepenger"
  push-image:
    required: false
    description: "Push the docker image (true|false)"
    default: "false"
  dockerfile:
    description: "Dockerfile"
    required: true
    default: "Dockerfile"
  docker_context:
    description: "Docker context"
    required: false
    default: "."
  docker_platforms:
    description: "Docker platforms"
    required: false
    default: "linux/amd64,linux/arm64"
  image_suffix:
    description: "Adds a suffiks to the generated docker image name"
    required: false
    default: ""
  build_args:
    description: "List of build-time variables"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # ratchet:docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # ratchet:docker/setup-buildx-action@v2
    - name: NAIS login
      uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # ratchet:nais/login@v0
      id: login
      with:
        team: ${{ inputs.namespace }}
    - name: Setup environment
      shell: bash
      run: |
        if [ ! -f "${{ inputs.dockerfile }}" ]; then
          echo "::error ::Dockerfile not found: ${{ inputs.dockerfile }}. Do you need to prepend context or working directory?"
          exit 1
        elif [ ! -d "${{ inputs.docker_context }}" ]; then
          echo "::error ::Docker context not found: ${{ inputs.docker_context }}."
          exit 1
        fi
    - name: Docker meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # ratchet:docker/metadata-action@v4
      id: meta
      with:
        images: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.image_suffix }}
        tags: |
          type=raw,value=${{ inputs.build-version }}
          # set latest tag for default branch (master)
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Bygg og push docker image
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # ratchet:docker/build-push-action@v4
      id: build_push
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.docker_platforms }}
        pull: true
        build-args: ${{ inputs.build_args }}
        push: ${{ inputs.push-image == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate SBOM, attest and sign image
      if: inputs.push-image == 'true'
      uses: nais/attest-sign@d8ec1989b5d1eb59809b050149713002f3de8e2d # ratchet:nais/attest-sign@v2.0.6
      with:
        image_ref: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.image_suffix }}@${{ steps.build_push.outputs.digest }}
