name: "Build and push docker image"
description: "Build and push docker image"
inputs:
  build-version:
    description: "Image tag for the docker image"
    required: true
  namespace:
    required: false
    description: "NAV team"
    default: "teamforeldrepenger"
  push-image:
    required: false
    description: "Push the docker image (true|false)"
    default: "false"
  dockerfile:
    description: "Dockerfile"
    required: true
    default: "Dockerfile"
  docker_context:
    description: "Docker context"
    required: false
    default: "."
  docker_platforms:
    description: "Docker platforms"
    required: false
    default: "linux/amd64,linux/arm64"
  image_suffix:
    description: "Adds a suffiks to the generated docker image name"
    required: false
    default: ""
  build_args:
    description: "List of build-time variables"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # ratchet:docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # ratchet:docker/setup-buildx-action@v2
    - name: NAIS login
      uses: nais/login@e7cf2c159677dc7c7d599feff5f808f2bf59c7cf # ratchet:nais/login@v0
      id: login
      with:
        team: ${{ inputs.namespace }}
    - name: Setup environment
      shell: bash
      run: |
        if [ ! -f "${{ inputs.dockerfile }}" ]; then
          echo "::error ::Dockerfile not found: ${{ inputs.dockerfile }}. Do you need to prepend context or working directory?"
          exit 1
        elif [ ! -d "${{ inputs.docker_context }}" ]; then
          echo "::error ::Docker context not found: ${{ inputs.docker_context }}."
          exit 1
        fi
    - name: Docker meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # ratchet:docker/metadata-action@v4
      id: meta
      with:
        images: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.image_suffix }}
        tags: |
          type=raw,value=${{ inputs.build-version }}
          # set latest tag for default branch (master)
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Bygg og push docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # ratchet:docker/build-push-action@v4
      id: build_push
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.docker_platforms }}
        pull: true
        build-args: ${{ inputs.build_args }}
        push: ${{ inputs.push-image == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Generate SBOM, attest and sign image
      if: inputs.push-image == 'true'
      uses: nais/attest-sign@e832aa0c77880b1725fc67b63c65a4374b658892 # ratchet:nais/attest-sign@v1.5.22
      env:
        TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
      with:
        image_ref: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.image_suffix }}@${{ steps.build_push.outputs.digest }}
