name: "Maven install"
description: "Maven install"

inputs:
  t-2c:
    description: "Thread config to use"
    required: false
    default: ""
  profil:
    description: "Maven profile to use (f.eks. sonar spesifisers -Psonar"
    required: false
    default: ""

outputs:
  build-version:
    description: "Build version"
    value: ${{ steps.generate-build-version.outputs.build-version }}

runs:
  using: "composite"
  steps:
    - name: Generate build version
      id: generate-build-version
      shell: bash
      run: echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Print build version
      shell: bash
      env:
        BUILD_VERSION: ${{ steps.generate-build-version.outputs.build-version }}
      run: echo "Generated build-version is $BUILD_VERSION"

    - name: Build artifacts
      shell: bash
      run: |
        echo "Building artifacts $BUILD_VERSION"
        mvn versions:set -DnewVersion="$BUILD_VERSION" -q -e -B
        mvn install $T_2C -ntp -e -B $PROFIL ${{ (inputs.skip-tests == 'true' && '-DskipTests') || '' }}
      env:
        TESTCONTAINERS_REUSE_ENABLE: true
        BUILD_VERSION: ${{ steps.generate-build-version.outputs.build-version }}
        T_2C: ${{ inputs.t-2c }}
        PROFIL: ${{ inputs.profil }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_ACTOR: ${{ github.actor }}
