name: Build app
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: Miljø versjon som skal brukes til bygg.
        default: 'ubuntu-latest'
      t-2c:
        required: false
        type: string
        description: Tråd konfig til maven.
        default: ''
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '25'
      use-reader:
        required: false
        type: boolean
        description: Hvilket token skal brukes?
        default: false
      working-directory:
        required: false
        default: .
        type: string

jobs:
  build-and-test:
    name: Build and test
    runs-on: ${{ (github.event.pull_request.user.login == 'dependabot[bot]' && 'ubuntu-latest') || inputs.runs-on }}
    outputs:
      build-version: ${{ steps.build-and-test.outputs.build-version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          fetch-depth: 0 # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # ratchet:actions/setup-java@v5.4.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven verify
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: mvn verify -ntp -e -B ${{ inputs.t-2c }}
        env:
          GITHUB_TOKEN: ${{ (github.actor != 'dependabot[bot]' && inputs.use-reader && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Clean up generated stuff before caching
        run: |
          if [[ -d "~/.m2/repository/no/nav/foreldrepenger" ]]; then
            rm ~/.m2/repository/no/nav/foreldrepenger -r
          fi
