name: Build app
# Gjenbrukbar workflow: bygger og tester en Maven-app, og bygger/pusher evt. Docker-image.
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: Miljø versjon som skal brukes til bygg.
        default: "ubuntu-latest"
      t-2c:
        required: false
        type: string
        description: Tråd konfig til maven.
        default: ""
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: "25"
      build-image:
        required: false
        type: boolean
        description: Skal docker image bygges?
        default: true
      push-image:
        required: false
        type: boolean
        description: Skal docker image pushes?
        default: false
      namespace:
        required: false
        type: string
        description: "The namespace to push images to"
        default: "teamforeldrepenger"
    outputs:
      build-version:
        description: "Build version"
        value: ${{ jobs.build-and-test.outputs.build-version }}
jobs:
  build-and-test:
    name: Build and test
    permissions:
      contents: read    # checkout av koden
      packages: read    # lese private @navikt Maven-pakker fra GitHub Packages under `mvn install`
      id-token: write   # OIDC mot NAIS/GAR for docker login + push + signering/attestering
    runs-on: ${{ (github.event.pull_request.user.login == 'dependabot[bot]' && 'ubuntu-latest') || inputs.runs-on }}
    env:
      TZ: "Europe/Oslo"
    outputs:
      build-version: ${{ steps.build-and-test.outputs.build-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          fetch-depth: 0 # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
          persist-credentials: false

      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # ratchet:actions/setup-java@v6.0.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Maven install and test
        id: build-and-test
        uses: navikt/fp-gha-workflows/.github/actions/build-maven-application@main # ratchet:exclude
        with:
          t-2c: ${{ inputs.t-2c }}

      - name: Bygg og push docker image
        if: inputs.build-image
        uses: navikt/fp-gha-workflows/.github/actions/build-push-docker-image@main # ratchet:exclude
        with:
          build-version: ${{ steps.build-and-test.outputs.build-version }}
          push-image: ${{ inputs.push-image }}
          namespace: ${{ inputs.namespace }}

      - name: Clean up generated stuff before caching
        shell: bash
        run: |
          rm -r ~/.m2/repository/no/nav/foreldrepenger
