name: Build app
# Gjenbrukbar workflow: kjører `mvn verify` (bygg + test), uten database.
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: Miljø versjon som skal brukes til bygg.
        default: "ubuntu-latest"
      t-2c:
        required: false
        type: string
        description: Tråd konfig til maven.
        default: ""
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: "25"
      working-directory:
        required: false
        default: .
        type: string

jobs:
  build-and-test:
    name: Build and test
    permissions:
      contents: read    # checkout av koden (public @navikt Maven-deps leses uten packages-perm)
    runs-on: ${{ (github.event.pull_request.user.login == 'dependabot[bot]' && 'ubuntu-latest') || inputs.runs-on }}
    outputs:
      build-version: ${{ steps.build-and-test.outputs.build-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          fetch-depth: 0 # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
          persist-credentials: false

      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # ratchet:actions/setup-java@v6.0.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Maven verify
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: mvn verify -ntp -e -B ${T_2C}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          T_2C: ${{ inputs.t-2c }}

      - name: Clean up generated stuff before caching
        run: |
          if [[ -d "~/.m2/repository/no/nav/foreldrepenger" ]]; then
            rm ~/.m2/repository/no/nav/foreldrepenger -r
          fi
