name: Upload assets to CDN
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag (build-version) å hente assets fra (eksempel 2023.03.10.080433-f821119)'
      image_suffix:
        required: true
        type: string
        description: 'Suffix på imaget som assets hentes fra (eksempel /engangsstonad)'
      destination:
        required: true
        type: string
        description: 'CDN-destinasjon, typisk appens vite base (eksempel /engangsstonad/soknad)'
      image_path:
        required: false
        type: string
        description: 'Sti til de bygde assetene inne i containeren'
        default: '/app/public'

jobs:
  upload-to-cdn:
    name: Upload assets to CDN
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Login GAR
        uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # ratchet:nais/login@v0
        id: login
        with:
          team: teamforeldrepenger
      - name: Extract assets from built image
        env:
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.image_suffix }}:${{ inputs.image }}
        run: |
          docker pull "$IMAGE"
          cid=$(docker create "$IMAGE")
          docker cp "$cid:${{ inputs.image_path }}" ./cdn-dist
          docker rm "$cid"
      - name: Upload static files to CDN
        id: upload
        uses: nais/deploy/actions/cdn-upload/v2@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # ratchet:nais/deploy/actions/cdn-upload/v2@v2
        with:
          team: teamforeldrepenger
          source: ./cdn-dist
          destination: ${{ inputs.destination }}
      - run: 'echo "uploaded file ${{ steps.upload.outputs.uploaded }}"'
