name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The enviroment to deployed to. Either dev, prod og both'
      platform:
        required: true
        type: string
        description: 'The platform/zone to deploy to. Either fss eller gcp'
      namespace:
        required: false
        type: string
        description: 'The namespace to deploy to.'
        default: 'teamforeldrepenger'
      issue-number:
        required: true
        type: string
        description: 'The deployment issue.'

jobs:
  promote:
    name: promote
    runs-on: 'ubuntu-latest'
    steps:
      - name: Get information from issue
        id: issue_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.get( {
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ inputs.issue-number }} })
            .then(response => {
              core.setOutput('sha', response.data.body);
              core.setOutput('title', response.data.title);
            });
      - name: Setter IMAGE som brukes i deploy filen
        run: echo "IMAGE=ghcr.io/${{ github.repository }}:$(echo ${{ steps.issue_comment.outputs.title }} | awk '{print $NF}')" >> $GITHUB_ENV

      - name: Checkout ${{ steps.issue_comment.outputs.sha }}
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ steps.issue_comment.outputs.sha }}

      - name: Utleder cluster ut i fra environment og platform
        run: echo "CLUSTER=${{ inputs.environment }}-${{ inputs.platform }}" >> $GITHUB_ENV

      - name: Deploy to ${{ env.CLUSTER }}
        if: startsWith(env.CLUSTER, 'dev-') || startsWith(env.CLUSTER, 'prod-')
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/${{ env.CLUSTER }}-${{ inputs.namespace }}.json

      - name: Oppdater kommentar med deployment status ved feil mot ${{ env.CLUSTER }}
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ inputs.issue-number }} }
            github.rest.issues.createComment({...issue,
                            body: 'promote til ${{ env.CLUSTER }} ${{ inputs.namespace }} feilet'})
            github.rest.issues.addLabels({...issue,
                            labels: ['deployment-failed']})
      - name: Oppdater kommentar med deployment status mot ${{ env.CLUSTER }}
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ inputs.issue-number }} }
            github.rest.issues.createComment({...issue,
                            body: 'promote til ${{ env.CLUSTER }} ${{ inputs.namespace }} utført'})
            github.rest.issues.addLabels({...issue,
                            labels: ['deployment','${{ env.CLUSTER }}-${{ inputs.namespace }}']})
