name: Deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Image navn"
      cluster:
        required: true
        type: string
        description: "The cluster to deploy to."
      namespace:
        required: false
        type: string
        description: "The namespace to deploy to."
        default: "teamforeldrepenger"
      app:
        required: true
        type: string
        description: "The app to deploy."
env:
  IMAGE: ${{ inputs.image }} # Brukes i naiserator.yaml
jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.cluster }}:${{ inputs.app }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
      - name: Deploy ${{ inputs.cluster }}
        uses: nais/deploy/actions/deploy@0bca2c7e607d30fd757a2a23fb7d07b3ff96d540 # ratchet:nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/${{ inputs.app }}/${{ inputs.cluster }}-${{ inputs.app }}.json
