name: Deploy

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      cluster:
        required: true
        type: string
        description: 'The cluster to deploy to (dev-fss|dev-gcp|prod-fss|prod-gcp)'
      namespace:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'teamforeldrepenger'
      gar:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'false'

env:
  IMAGE: ${{ inputs.image }} # Brukes i naiserator.yaml

jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.cluster }}:${{ inputs.namespace }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy ${{ inputs.cluster }} fra Github
        if: inputs.gar == 'false'
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/${{ inputs.cluster }}-${{ inputs.namespace }}.json

      - name: Login GAR
        uses: nais/login@v0
        if: inputs.gar == 'true'
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: teamforeldrepenger

      - name: Deploy ${{ inputs.cluster }} fra GAR
        if: inputs.gar == 'true'
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}:${{ inputs.image }}
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/${{ inputs.cluster }}-${{ inputs.namespace }}.json
