name: Maven Dependency Submission
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '25'
jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ (github.actor != 'dependabot[bot]' && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4
      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Generate build version
        id: generate-build-version
        shell: bash
        run: echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Print build version
        shell: bash
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"
      - name: Build artifactsM
        shell: bash
        run: |
          echo "Building artifacts ${{ steps.generate-build-version.outputs.build-version }}"
          mvn versions:set -DnewVersion="${{ steps.generate-build-version.outputs.build-version }}" -q -e -B
      - name: Submit Dependency Snapshot to Github Security
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8
        with:
          maven-args: -DskipTests
