name: Maven Dependency Submission
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '17'

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup java and maven
        uses: navikt/fp-gha-workflows/.github/actions/setup-java-and-maven@main
        with:
          github-token: ${{ (github.actor != 'dependabot[bot]' && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}

      - name: Generate build version
        id: generate-build-version
        shell: bash
        run: echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Print build version
        shell: bash
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

      - name: Build artifacts
        shell: bash
        run: |
          echo "Building artifacts ${{ steps.generate-build-version.outputs.build-version }}"
          mvn versions:set -DnewVersion="${{ steps.generate-build-version.outputs.build-version }}" -s settings.xml -q -e -B

      - name: Submit Dependency Snapshot to Github Security
        uses: advanced-security/maven-dependency-submission-action@c5ad0fd6b977364190852883b46728f25a9617c3
        with:
          settings-file: settings.xml
          maven-args: -DskipTests
