name: Promote to cluster

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The enviroment to deployed to. Either dev, prod og both'
      platform:
        required: true
        type: string
        description: 'The platform/zone to deploy to. Either fss eller gcp'
      namespace:
        required: false
        type: string
        description: 'The namespace to deploy to.'
        default: 'teamforeldrepenger'
      issue-number:
        required: true
        type: string
        description: 'The deployment issue.'

jobs:
  promote-dev:
    name: Deploy dev-$${{ inputs.platform }}
    if: contains('dev', inputs.environment)
    uses: navikt/fp-gha-workflows/.github/workflows/promote-helper.yml@rydding
    with:
      issue-number: ${{ inputs.issue-number }}
      namespace: ${{ inputs.namespace }}
      cluster: dev-${{ inputs.platform }}
    secrets: inherit

  promote-prod:
    name: Deploy prod-$${{ inputs.platform }}
    needs: promote-dev
    if: success() && contains('prod', inputs.environment)
    uses: navikt/fp-gha-workflows/.github/workflows/promote-helper.yml@rydding
    with:
      issue-number: ${{ inputs.issue-number }}
      namespace: ${{ inputs.namespace }}
      cluster: prod-${{ inputs.platform }}
    secrets: inherit
