name: Release feature
# Gjenbrukbar workflow: setter release-versjon og publiserer (`mvn deploy`) artefakter.
on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        description: 'The release version.'
      java-version:
        required: false
        type: string
        description: 'Java SDK versjon som skal brukes.'
        default: '25'
      mvn-projects:
        required: false
        type: string
        description: 'Comma-delimited list of specified reactor projects to build instead of all projects.'
        default: ''
      release-profiles:
        required: false
        type: string
        description: 'Profiles which should be used when releasing an artifact.'
        default: '-Pdeploy'
      release-branch:
        required: false
        type: string
        description: 'Hvilken branch skal releases. Default master.'
        default: 'master'
      release-file:
        required: false
        type: string
        description: 'Hvilken pom.xml fil skal releases. Default empty.'
        default: ''
      working-directory:
        required: false
        default: .
        type: string
jobs:
  build:
    name: Release
    permissions:
      contents: read    # checkout av koden
      packages: write   # publisere Maven-artefakter til GitHub Packages (`mvn deploy`)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ inputs.release-branch }}
      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # ratchet:actions/setup-java@v5.7.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Publish artifacts
        working-directory: ${{ inputs.working-directory }}
        run: |
          mvn -B versions:set -DnewVersion=${{ inputs.release-version }} ${{ inputs.release-file }}
          mvn -B -Dmaven.wagon.http.pool=false -DskipTests clean deploy ${{ inputs.mvn-projects }} ${{ inputs.release-profiles }} ${{ inputs.release-file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
