name: "Statisk Code Analysis"
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '21'
      language:
        required: false
        type: string
        description: Språk som skal scannes
        default: 'java'
      use-reader:
        required: false
        type: boolean
        description: Hvilket token skal brukes?
        default: false
      runs-on:
        required: false
        type: string
        description: Hvilken runner som skal brukes i bygg.
        default: 'ubuntu-latest'
jobs:
  codeql:
    name: CodeQL Analyse
    runs-on: ${{ inputs.runs-on }}
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Last ned bygg artefakter
        uses: actions/download-artifact@v4
        with:
          name: built-code
      - name: Setup java and maven
        uses: navikt/fp-gha-workflows/.github/actions/setup-java-and-maven@main
        with:
          github-token: ${{ (github.actor != 'dependabot[bot]' && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'
          config-file: navikt/fp-gha-workflows/.github/codeql/codeql-config.yml@main
      - name: CodeQL analyse
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:java"
  sonar:
    name: Sonar Analyse
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Last ned bygg artefakter
        uses: actions/download-artifact@v4
        with:
          name: built-code
      - name: Setup java and maven
        uses: navikt/fp-gha-workflows/.github/actions/setup-java-and-maven@main
        with:
          github-token: ${{ (github.actor != 'dependabot[bot]' && secrets.READER_TOKEN) || secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}
      - name: Sonar analyse
        run: |
          mvn jacoco:report jacoco:report-aggregate sonar:sonar -s settings.xml -e -q -B -Djacoco.destFile=$(pwd)/target/jacoco.exec -Psonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}